// Mapas: cada caractere é uma casa de 10 cm. A primeira linha é o lado de longe do tabuleiro.
//   #  parede          .  chão            _  vazio (cai)      S  início         G  toca (chegada)
//   *  estrela         o  buraco          C  bandeira         ~  gelo           m  lama/caramelo
//   > < ^ v  seta que empurra             B  pula-pula        k  chave          D  porta
//   1 2  par de portais                   3 4  outro par de portais
// Objetos móveis ficam em "objects", com posições em [linha, coluna]:
//   { type: "spinner", at: [l, c], arm: casas, speed: rad/s }
//   { type: "slider", from: [l, c], to: [l, c], size: [largura, altura], period: segundos }
// Para um nível novo: acrescente um objeto aqui (e rode "npm run niveis" para conferir).

export const LEVELS = [
  {
    name: "Primeiros Passos",
    theme: "jardim",
    hint: "Leve a bolinha até a toca brilhante!",
    friend: "coelhinho",
    map: [
      "###########",
      "#G...*....#",
      "#.........#",
      "#######...#",
      "#.........#",
      "#....*....#",
      "#...#######",
      "#.........#",
      "#.*.......#",
      "#........S#",
      "###########",
    ],
  },
  {
    name: "Caminho Torto",
    theme: "jardim",
    hint: "Corredores estreitos e buracos no fim!",
    friend: "joaninha",
    map: [
      "#############",
      "#S#.....#..*#",
      "#.#.###.#.#.#",
      "#.#.#*#.#.#.#",
      "#.#.#.#...#.#",
      "#...#.#####.#",
      "#####.......#",
      "#*....#######",
      "#####.......#",
      "###########.#",
      "#.o.....o...#",
      "#G..o.......#",
      "#############",
    ],
  },
  {
    name: "Pontes do Jardim",
    theme: "jardim",
    hint: "Pontes sem parede: vá devagar! A bandeira guarda o seu lugar.",
    friend: "sapinho",
    map: [
      "_____________",
      "_S...___..G._",
      "_....___*..._",
      "__..______.._",
      "__..______.._",
      "__..______.._",
      "_.C....___.._",
      "_*..o......*_",
      "_......___.._",
      "_____________",
    ],
  },
  {
    name: "Lago Congelado",
    theme: "gelo",
    hint: "O gelo escorrega muito!",
    friend: "gatinho",
    map: [
      "#############",
      "#S.~~~~~~~~*#",
      "#.~~~~~~~~~~#",
      "#.~~~~o~~*~~#",
      "#.~~~~~~~~~~#",
      "###~~~###~###",
      "#*~~~~#~~~~.#",
      "#.~~o~#~~o~.#",
      "#.~~~~#~~~~.#",
      "#.....#...G.#",
      "#############",
    ],
  },
  {
    name: "Escorregador",
    theme: "gelo",
    hint: "As setas empurram a bolinha!",
    friend: "coelhinho",
    map: [
      "#############",
      "#S.>>>>>....#",
      "#########.#.#",
      "#*<<<<....#.#",
      "###########.#",
      "#.~~~~~~~~~.#",
      "#.~~o~~~*~~.#",
      "#.~~~~~~o~~.#",
      "#.###########",
      "#v..........#",
      "#v.o..o...o.#",
      "#G....*.o...#",
      "#############",
    ],
  },
  {
    name: "Chave de Gelo",
    theme: "gelo",
    hint: "Pegue a chave para abrir a porta. Cuidado com os blocos!",
    friend: "joaninha",
    map: [
      "#############",
      "#S....#....k#",
      "#.###.#.###.#",
      "#.#*..#...#.#",
      "#.#####.#.#.#",
      "#.......#...#",
      "######D######",
      "#...........#",
      "##~~~~~~~~~.#",
      "##~~~~o~~*~.#",
      "#.~~~~~~~~~.#",
      "#G#.......*.#",
      "#############",
    ],
    objects: [
      { type: "slider", from: [7, 2], to: [7, 10], size: [0.9, 0.9], period: 5 },
      { type: "slider", from: [11, 9], to: [11, 3], size: [0.9, 0.9], period: 4 },
    ],
  },
  {
    name: "Pinball de Doces",
    theme: "doces",
    hint: "As balas fazem a bolinha quicar!",
    friend: "sapinho",
    map: [
      "#############",
      "#...*#G#*...#",
      "#.B..#.#..B.#",
      "#...o#.#o...#",
      "#.B.......B.#",
      "#...B.o.B...#",
      "#o.........o#",
      "#..B..*..B..#",
      "#.....B.....#",
      "#..o.....o..#",
      "#.....S.....#",
      "#############",
    ],
  },
  {
    name: "Portais Mágicos",
    theme: "doces",
    hint: "Entre nos portais! O caramelo deixa a bolinha lenta.",
    friend: "gatinho",
    map: [
      "#############",
      "#S...#2..mm*#",
      "#.mm.#.o.mm.#",
      "#.mm.#.....3#",
      "#*..1#..o...#",
      "#############",
      "#4....o...G.#",
      "#.mmm...mmm.#",
      "#.mmm...mmm.#",
      "#....*......#",
      "#############",
    ],
    objects: [{ type: "spinner", at: [7, 6], arm: 1.3, speed: 1.4 }],
  },
  {
    name: "Moinho de Pirulito",
    theme: "doces",
    hint: "Os pirulitos giram: passe na hora certa!",
    friend: "coelhinho",
    map: [
      "_____________",
      "_...___....*_",
      "_G.........._",
      "_...___...o._",
      "_______....._",
      "__________.__",
      "__________.__",
      "__________.__",
      "_________.C._",
      "_....____..._",
      "_S.........._",
      "_*...____..*_",
      "_____________",
    ],
    objects: [
      { type: "spinner", at: [2, 9], arm: 1.5, speed: 1.0 },
      { type: "spinner", at: [10, 10], arm: 1.2, speed: -1.3 },
    ],
  },
  {
    name: "Castelo nas Nuvens",
    theme: "castelo",
    finale: true,
    hint: "GRANDE FINAL! Três partes até o trono.",
    friend: "joaninha",
    stages: [
      {
        hint: "Parte 1: o portão. Pegue a chave!",
        map: [
          "###########",
          "#S...o...k#",
          "#..B...B..#",
          "#.o...o...#",
          "#...B...o.#",
          "#####D#####",
          "#.........#",
          "#.###.###.#",
          "#.#*o.o.#.#",
          "#...#G#...#",
          "###########",
        ],
      },
      {
        hint: "Parte 2: o salão de gelo.",
        map: [
          "###########",
          "#S~~~~~~~*#",
          "#~~~~~~~~~#",
          "#~o~~~~~o~#",
          "#~~~~~~~~~#",
          "#~~~o~o~~~#",
          "########v##",
          "#.o..o..v.#",
          "#G<<<<<<<.#",
          "#..o...o..#",
          "###########",
        ],
        objects: [{ type: "spinner", at: [3, 5], arm: 1.8, speed: 0.9 }],
      },
      {
        hint: "Parte 3: a torre. O trono está logo ali!",
        map: [
          "___________",
          "_....___.2_",
          "_G........_",
          "_....___*._",
          "___________",
          "___________",
          "__.....____",
          "__.o..1____",
          "__..o..____",
          "__..S..____",
          "___________",
        ],
        objects: [
          { type: "slider", from: [0.4, 6], to: [3.6, 6], size: [0.9, 0.9], period: 3.4 },
          { type: "spinner", at: [2, 3], arm: 1.0, speed: 1.6 },
        ],
      },
    ],
  },
];

export const TOTAL_STARS = LEVELS.reduce((sum, level) => sum + (level.finale ? level.stages.length : 3), 0);

// Lista de tabuleiros de um nível (o final tem três partes).
export function stagesOf(level) {
  return level.finale ? level.stages : [level];
}
