// Cores e estilo de cada mundo. Para um mundo novo: um objeto aqui e "theme" no nível.
export const THEMES = {
  jardim: {
    label: "Jardim",
    floorA: "#8fd96b",
    floorB: "#82cc5e",
    floorSide: "#6bb04a",
    underTop: "#9a6a42",
    underBottom: "#5e3d26",
    wall: "hedge",
    wallSide: "#3f9d45",
    wallTop: "#6fd06a",
    accent: "#ff7eb3",
    ice: "#a8e6ff",
    mud: "#8a5a34",
    bumper: "#ff6f91",
    sky: { zenith: "#3f8fe0", mid: "#93cdf6", horizon: "#ffe1c2", sun: "#ffd29a" },
    cloud: ["#f2dcd6", "#ffffff"],
    fog: "#f6e3cf",
    particles: { color: "#fff6a8", kind: "pollen" },
    decor: "trees",
    stars: 0,
  },
  gelo: {
    label: "Gelo",
    floorA: "#eef6ff",
    floorB: "#e1edfb",
    floorSide: "#bcd3ee",
    underTop: "#9fb8d6",
    underBottom: "#5d7799",
    wall: "snow",
    wallSide: "#cfe6fb",
    wallTop: "#ffffff",
    accent: "#4fc3f7",
    ice: "#8fdcff",
    mud: "#7d8fa8",
    bumper: "#7aa7ff",
    sky: { zenith: "#5a7fd6", mid: "#a9d4f5", horizon: "#ffe0ef", sun: "#fff0d8" },
    cloud: ["#dfe6f5", "#ffffff"],
    fog: "#e6eefa",
    particles: { color: "#ffffff", kind: "snow" },
    decor: "pines",
    stars: 0,
  },
  doces: {
    label: "Doces",
    floorA: "#f7d9a8",
    floorB: "#f2cb90",
    floorSide: "#d9a565",
    underTop: "#fff1e0",
    underBottom: "#e58db0",
    wall: "chocolate",
    wallSide: "#7b4a2e",
    wallTop: "#ff9ecf",
    accent: "#ff5fa2",
    ice: "#bff0ff",
    mud: "#d9822b",
    bumper: "#ff5f7e",
    sky: { zenith: "#7a5be0", mid: "#f3a6d0", horizon: "#ffd29e", sun: "#ffe0a8" },
    cloud: ["#ffc8e4", "#fff4fb"],
    fog: "#fbd7e6",
    particles: { color: "#ffd6f0", kind: "sugar" },
    decor: "candy",
    stars: 0,
  },
  castelo: {
    label: "Castelo",
    floorA: "#e4dff2",
    floorB: "#d6cfea",
    floorSide: "#a79fc4",
    underTop: "#b7afd0",
    underBottom: "#6f6596",
    wall: "stone",
    wallSide: "#9d93c2",
    wallTop: "#c9c0e8",
    accent: "#ffd34d",
    ice: "#a6e4ff",
    mud: "#7a6a9a",
    bumper: "#ffb347",
    sky: { zenith: "#1d1a5c", mid: "#5a4aa8", horizon: "#ff9fb6", sun: "#ffd9a0" },
    cloud: ["#b9a9e0", "#f4eaff"],
    fog: "#b8a5df",
    particles: { color: "#fff3b0", kind: "stars" },
    decor: "towers",
    stars: 1,
  },
};
